import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { fetchArticles, fetchCategories } from '../http';
import { IArticle, ICategory, ICollectionResponse } from '../types';
import { AxiosResponse } from 'axios';
import Tabs from '../components/Tabs';
import ArticleList from '../components/ArticleList';
import qs from "qs";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: {
    items: IArticle[];
  }
}

const Home: NextPage<IPropTypes> = ({ categories, articles }) => {

  console.log('categories', categories)
  console.log('articles', articles)

  const handleOnSearch = (query: String) => {
    console.log("handling search")
  }

  return (
    <div>
      <Head>
        <title>Blog Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} handleOnSearch={handleOnSearch} />
      <ArticleList articles={articles.items} />
    </div>
  )
};

export const getServerSideProps: GetServerSideProps = async () => {

  //articles
  const options = {

    populate: ['author.avatar'],
    sort: ['id:desc'],
  }

  const queryString = qs.stringify(options)
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticles(queryString);

  //categories

  const {
    data: categories
  }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  console.log('categories', categories)
  console.log('articles', articles)

  return {
    props: {
      categories: {
        items: categories.data
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination
      }
    }
  }
}

export default Home
