import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { fetchArticles, fetchCategories } from '../http';
import { IArticle, ICategory, ICollectionResponse } from '../types';
import { AxiosResponse } from 'axios';
import Tabs from '../components/Tabs';

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: {
    items: IArticle[];
  }
}

const Home: NextPage<IPropTypes> = ({ categories, articles }) => {

  console.log('categories', categories)

  return (
    <div>
      <Head>
        <title>Blog Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} />
      {/* Articles */}
    </div>
  )
};

export const getServerSideProps: GetServerSideProps = async () => {

  //articles
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticles();

  //categories

  const {
    data: categories
  }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  console.log('categories', categories)

  return {
    props: {
      categories: {
        items: categories.data
      },
      articles: {
        itmes: articles.data,
        pagination: articles.meta.pagination
      }
    }
  }
}

export default Home
